resolver: lts-8.13

packages:
  - '.'
  - 'tensorflow-mnist-deptyped'
  - location:
      git: https://github.com/tensorflow/haskell.git
      commit: a8405d15a22fc62dce8e868623e12a83e11f56b8
    subdirs:
      - tensorflow
      - tensorflow-core-ops
      - tensorflow-logging
      - tensorflow-mnist
      - tensorflow-mnist-input-data
      - tensorflow-opgen
      - tensorflow-ops
      - tensorflow-proto
      - tensorflow-records
      - tensorflow-records-conduit
      - tensorflow-test
    extra-dep: true
extra-deps:
  - proto-lens-protobuf-types-0.2.1.0
  - proto-lens-0.2.2.0
  - proto-lens-protoc-0.2.2.3
  - proto-lens-descriptors-0.2.2.0
  - snappy-0.2.0.2
  - snappy-framing-0.1.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
